# Generated by Django 3.0.8 on 2020-08-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('main_image', models.ImageField(upload_to='main_image/%Y/%m/%d/')),
                ('second_images', models.ImageField(upload_to='second_images/%Y/%m/%d/')),
                ('slug', models.SlugField()),
                ('small_description', models.TextField()),
                ('content', models.TextField()),
                ('categories', models.ManyToManyField(to='blogs.Category')),
            ],
        ),
    ]
