# Generated by Django 3.0.8 on 2020-08-05 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200805_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publish_date_now',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
